# platform.app.yaml
name: app
type: 'php:8.3'
disk: 2048

relationships:
    database: 'postgresql:postgresql'

variables:
    env:
        APP_ENV: 'prod'
        APP_SECRET: 'votre_secret_symfony'
        CORS_ALLOW_ORIGIN: 'https://votre-application.vercel.app'

mounts:
    '/public/uploads': 'shared:files/uploads'

web:
    locations:
        '/':
            root: 'public'
            passthru: '/index.php'
            scripts: true
            allow: true
